In [1]:
import pandas as pd
print("#printing csv file")
csv1=pd.read_csv("TestNewHeader.csv")
print(csv1)
print("\n")

#printing csv file
    1   2   3
0   3   5   9
1   4  34   5
2   5   6  23
3  56   4   5
4   4   6   6




In [4]:
#getting total index
print("#getting total index")
print(csv1.index)
print("\n")

#getting total column name
print("#getting total column name")
print(csv1.columns)
print("\n")


#getting total index
RangeIndex(start=0, stop=5, step=1)


#getting total column name
Index(['1', '2', '3'], dtype='object')




In [5]:
#using describe method for getting mean,min value,max value
print("#using describe method for getting mean,min value,max value")
print(csv1.describe())
print("\n")

#getting perticular row of data from top
print("#getting perticular row of data from top")
print(csv1.head(2))
print("\n")

#getting perticular row of data from bottom
print("#getting perticular row of data from bottom")
print(csv1.tail(2))
print("\n")


#using describe method for getting mean,min value,max value
               1          2          3
count   5.000000   5.000000   5.000000
mean   14.400000  11.000000   9.600000
std    23.265855  12.884099   7.668116
min     3.000000   4.000000   5.000000
25%     4.000000   5.000000   5.000000
50%     4.000000   6.000000   6.000000
75%     5.000000   6.000000   9.000000
max    56.000000  34.000000  23.000000


#getting perticular row of data from top
   1   2  3
0  3   5  9
1  4  34  5


#getting perticular row of data from bottom
    1  2  3
3  56  4  5
4   4  6  6




In [11]:
#here we can also use the string slicing
print("#here we can also use the string slicing")
print(csv1[:3])
print("\n")
print(csv1[2:4])
print("\n")


#here we can also use the string slicing
   1   2   3
0  3   5   9
1  4  34   5
2  5   6  23


    1  2   3
2   5  6  23
3  56  4   5




In [12]:
#converting the index into array
print("#converting the index into array")
print(csv1.index.array)
print("\n")

#converting the hole data into array with the help of numpy array.
print("#converting the hole data into array with the help of numpy array.")
print(csv1.to_numpy())
print("\n")

#converting the hole data into array with the help of other method.
print("#converting the hole data into array with the help of other method.")
import numpy as np
v=np.asarray(csv1)
print(v)
print("\n")


#converting the index into array
<NumpyExtensionArray>
[0, 1, 2, 3, 4]
Length: 5, dtype: int64


#converting the hole data into array with the help of numpy array.
[[ 3  5  9]
 [ 4 34  5]
 [ 5  6 23]
 [56  4  5]
 [ 4  6  6]]


#converting the hole data into array with the help of other method.
[[ 3  5  9]
 [ 4 34  5]
 [ 5  6 23]
 [56  4  5]
 [ 4  6  6]]




In [13]:
#printing ascending order to descending order
print("#printing ascending order to descending order")
var=csv1.sort_index(axis=0,ascending=False)
print(var)
print("\n")

#printing ascending order to descending order
    1   2   3
4   4   6   6
3  56   4   5
2   5   6  23
1   4  34   5
0   3   5   9




In [14]:
#changing the data into csv file
print("#changing the data into csv file")
csv1["1"][0]=25
print(csv1)
print("\n")

#changing the data into csv file other method
print("#changing the data into csv file other method")
csv1.loc[0,"2"]="python"
print(csv1)
print("\n")


#changing the data into csv file
    1   2   3
0  25   5   9
1   4  34   5
2   5   6  23
3  56   4   5
4   4   6   6


#changing the data into csv file other method
    1       2   3
0  25  python   9
1   4      34   5
2   5       6  23
3  56       4   5
4   4       6   6




C:\Users\Gopal Sharma\AppData\Local\Temp\ipykernel_13744\2898690102.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  csv1["1"][0]=25
C:\Users\Gopal Sharma\AppData\Local\Temp\ipykernel_13744\2898690102.py:9: FutureWarning: Setting an item 

In [17]:
#other use of loc function in pandas that loc function ki help se hum perticular row and perticular column ki value ko get kar sakte hai.
print("#other use of loc function in pandas that loc function ki help se hum perticular row and perticular column ki value ko get kar sakte hai.")
#print(csv1)
var=csv1.loc[[3,4],["2","3"]]
print(var)
print("\n")

#other use of loc function in pandas that loc function ki help se hum perticular row and perticular column ki value ko get kar sakte hai.
   2  3
3  4  5
4  6  6




In [5]:

#getting complete data of row and column
print("#getting complete data of row and column")
var=csv1.loc[:,["2","3"]]
print(var)
print("\n")
var=csv1.loc[[3,4],:]
print(var)
print("\n")

print("#iloc function , iloc function gives the perticular data")
#iloc function , iloc function gives the perticular data
print("csv1.iloc[1,0]=",csv1.iloc[1,0])
print("csv1.iloc[1,1]=",csv1.iloc[1,1])
print("csv1.iloc[3,2]=",csv1.iloc[3,2])
print("\n")

var=csv1.iloc[[3,4],:]
print(var)
print("\n")

var=csv1.iloc[[3,4],:].values
print(var)
print("\n")

#getting complete data of row and column
    2   3
0   5   9
1  34   5
2   6  23
3   4   5
4   6   6


    1  2  3
3  56  4  5
4   4  6  6


#iloc function , iloc function gives the perticular data
csv1.iloc[1,0]= 4
csv1.iloc[1,1]= 34
csv1.iloc[3,2]= 5


    1  2  3
3  56  4  5
4   4  6  6


[[56  4  5]
 [ 4  6  6]]




In [25]:
print("#drop method , drop method se hum kisi bhi column or row ko drop kar sakte hai.")
#drop method , drop method se hum kisi bhi column or row ko drop kar sakte hai.
#Note:column ko delete karne ke liye axis=1 likhte hai or row ko delete karne ke liye axis=0 likhate hai.
print(csv1.drop("1",axis=1))
print("\n")
print(csv1.drop(4,axis=0))
print("\n")

#drop method , drop method se hum kisi bhi column or row ko drop kar sakte hai.
        2   3
0  python   9
1      34   5
2       6  23
3       4   5
4       6   6


    1       2   3
0  25  python   9
1   4      34   5
2   5       6  23
3  56       4   5


